version: '3.8'
services:
  
  mysql:
    build: ./database
    ports:
     - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: dummypassword 
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: QR_CODE_SYSTEM
    volumes:
      - ./database/sqls:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
    mem_limit: 500M
    cpus: 1

  web: 
    build: ./app
    command: go run main.go
    ports:
      - "8080:8080"
    mem_limit: 500M
    cpus: 1
